[package]
name = "dungeoncrawl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib="~0.8.1"
legion="=0.3.1"

[profile.release]
strip = true
opt-level = "z"
lto = true
panic = "abort"
